steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/pos-backend:$_TAG', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/pos-backend:$_TAG']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - pos-backend
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/pos-backend:$_TAG
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --cpu=1
      - --memory=256Mi
      - --port=8080
      - --concurrency=80
      - --min-instances=0
      - --max-instances=1
      - --set-env-vars=NODE_ENV=production
substitutions:
  _REGION: us-central1
  _REPO: pos-artifacts
  _TAG: latest
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/pos-backend:$_TAG'

