name: publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: smoke test
        run: echo "workflow runs OK"
